Add OP_PICK and OP_ROLL
thunderbiscuit/opcode-explained pull request #14
Opened 2024-08-14 21:36 UTC by RedVelvetZip

Added pages for OP_PICK and OP_ROLL as well as updated config to reflect their paths in the menu

2024-08-15 17:36 UTC, thunderbiscuit requested changes
Thanks for the new pages! You need a quick rebase to pick up the latest from master, and I left a few small comments, but otherwise looks good.

2024-08-15 17:36 UTC, thunderbiscuit commented on opcodes/OP_PICK.md
> +Copying the nth stack item when n==2 with four five items (i.e., the third item from the top copies to the top):
> with four five items

I think you mean `with five items` here maybe?

2024-08-15 17:36 UTC, thunderbiscuit commented on opcodes/OP_PICK.md
> +**Byte representation:** `0x7b`
OP_PICK is 121, and therefore 0x79

2024-08-15 17:36 UTC, thunderbiscuit commented on opcodes/OP_ROLL.md
> +[`OP_ROLL`](./OP_ROLL.md) is used to a select a stack item and move it to the top.
Typo in this sentence with the extra "a".

2024-08-15 17:36 UTC, thunderbiscuit commented on opcodes/OP_ROLL.md
> +Moving the nth stack item when n==2 with four five items (i.e., the third item from the top moves to the top):
Same as above. "four five items" extra word.

2024-08-15 17:38 UTC, thunderbiscuit commented
I think maybe a quick mention on both pages that those operations are 0-based would be good—the number 2 will reach 3 deep in the stack (or maybe it's just too obvious? Let me know what you think).

2024-08-19 19:29 UTC, RedVelvetZip commented
thanks for the review. changes made and rebased to match the new config formatting

2024-09-17 19:29 UTC, thunderbiscuit commented
Sorry I totally forgot to merge this! ACK e27dc16ae8a33caa6243a11885162d5d34f9a719.

I'll just do a quick cleanup of commit history and it's good to go.

2024-09-17 19:43 UTC, merged